version: '3.7'

services:
  app:
    build: .
    container_name: nuxt-app
    restart: always
    ports:
      - '3000:3000'
    command: 'npm run start'
    env_file: .env
    networks:
      - classroom-network

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/certbot/www/:/var/www/certbot/
        - certbot_volume:/etc/letsencrypt/
    networks:
      - classroom-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_volume:/etc/letsencrypt/
      - ./nginx/certbot/www/:/var/www/certbot/
    command: certonly --webroot -w /var/www/certbot --force-renewal --email slavik46111@gmail.com -d bezpart.ru --agree-tos
    networks:
      - classroom-network

networks:
  default:
    external: 
      name: classroom-network
  classroom-network:
    name: classroom_backend_classroom-network
    external: true

volumes:
  certbot_volume:
    external: True
